"""add duration

Revision ID: 0113e08f334f
Revises: 9f6d6fae46bb
Create Date: 2024-10-02 00:01:08.333461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0113e08f334f'
down_revision: Union[str, None] = '9f6d6fae46bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('duration', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'duration')
    # ### end Alembic commands ###
