"""add music duration

Revision ID: 3e5ab0deeec0
Revises: 8f2eb5b67766
Create Date: 2024-10-01 15:20:18.454168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5ab0deeec0'
down_revision: Union[str, None] = '8f2eb5b67766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music', 'duration')
    # ### end Alembic commands ###
