"""init

Revision ID: 631c4f19a113
Revises: 623dc38745f9
Create Date: 2024-10-01 23:14:59.557359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631c4f19a113'
down_revision: Union[str, None] = '623dc38745f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('file_static_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'music', ['file_static_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'music', type_='unique')
    op.drop_column('music', 'file_static_path')
    # ### end Alembic commands ###
