"""add user fav

Revision ID: 7fd2abbc384c
Revises: 2e3ca29e21f5
Create Date: 2024-10-06 19:01:28.403067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd2abbc384c'
down_revision: Union[str, None] = '2e3ca29e21f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_playlist', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite_playlist')
    # ### end Alembic commands ###
