"""music file nullable

Revision ID: 8f2eb5b67766
Revises: 9149e3c8a19f
Create Date: 2024-10-01 15:03:12.145060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2eb5b67766'
down_revision: Union[str, None] = '9149e3c8a19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('music', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
